### ISSUE TITLE
Does this code still works? why did i managa.py runserver it came out nothing

### ISSUE THREAD

**Issue by ANDREWLWZ** [michaelikoko/Poller#1]

**Comment by michaelikoko** [comment]
Hey Andre, thanks for pointing out an issue. In the recent commit I made, I split the settings into settings/dev.py(Used locally in development) and settings/production.py(Used in production). In order to run locally:
- Clone the repository
- Create a python virtual environment
- Activate python virtual environment
- Run: pip install -r requirements.txt
- Change directory to where manage.py file lives
- Run: python3 manage.py migrate
- Run the local development server: python3 manage.py runserver
